version: '2'

services:
  db:
    container_name: mysql_container
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: "db_mopga"
       MYSQL_USER: 'test'
       MYSQL_PASSWORD: 'admin'
       MYSQL_ROOT_PASSWORD: 'admin'
    # Volume sur le fichier dump.sql, fichier qui contient la base de données
    # avec un minimum d'information, notamment les 2 utilisateurs
    # admin et uti (utilisateur que le professeur a demandé)
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  web:
    container_name: django_container
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - db

  # Utilisation de Portainer pour une visualisation graphique Docker
  # utile pour le débogage
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock